name: Deploy to anjaneya

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest on anjaneya
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 100.73.205.101
          username: sreeh007
          key: ${{ secrets.ANJANEYA_SSH_KEY }}
          script: |
            cd ~/grabha-web && git pull origin main
